### ISSUE TITLE
Timezone handling different from ElasticSearch's date_histogram

### ISSUE THREAD

**Issue by andrewclegg** [bleskes/elasticfacets#1]
We are running queries like these:

(1) date_histogram

``` javascript
{
  "query": {
    "filtered": {
      "query": {
        "range": {
          "datetime": {
            "from": "2012-07-01T00:00:00.000Z",
            "to": "2012-07-08T00:00:00.000Z"
          }
        }
      }
    }
  },
  "facets": {
    "published": {
      "date_histogram": {
        "field": "datetime",
        "interval": "day"
      }
    }
  }
}
```

(2) faceted_date_histogram

``` javascript
{
  "query": {
    "filtered": {
      "query": {
        "range": {
          "datetime": {
            "from": "2012-07-01T00:00:00.000Z",
            "to": "2012-07-08T00:00:00.000Z",
            "include_upper": false
          }
        }
      }
    }
  },
  "facets": {
    "gender": {
      "faceted_date_histogram": {
        "field": "datetime",
        "interval": "day",
        "facet": {
          "terms": {
            "field": "gender"
          }
        }
      }
    }
  }
}
```

In case 1, the timestamps on the buckets are:

1341100800000 - Sun, 01 Jul 2012 00:00:00 UTC
1341187200000 - Mon, 02 Jul 2012 00:00:00 UTC
etc.

In case 2, the timestamps are:

1341097200000 - Sat, 30 Jun 2012 23:00:00 UTC
1341183600000 - Sun, 01 Jul 2012 23:00:00 UTC
etc.

N.B. the server's timezone is currently on British Summer Time (GMT+1), so if you add the server's timezone offset, they line up.

**Comment by bleskes** [comment]
Hi Andrew,

You are right. There was still a default value set to Amsterdam time zone. I fixed it on master. I also uploaded a new snapshot build you can use.

I'm closing this bug. If it doesn't work for you please re open.

Cheers,
Boaz

**Comment by andrewclegg** [comment]
This works perfectly now, thanks again!
