### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by mdojwa** [bleskes/elasticfacets#4]
Hi,

I use ES version 0.20.1. I installed plugin using bin/plugin -install bleskes/elasticfacets/0.2. After starting ES I get:
[2013-01-31 20:02:35,427][INFO ][org.leskes.elasticsearch.plugin.elasticfacets.ElasticFacetsPlugin] ElasticFacets plugin initialized
[2013-01-31 20:02:35,431][INFO ][plugins                  ] [Arena] loaded [ElasticFacetsPlugin], sites []

but localhost:9200/_nodes/cache/fields/stats does not work:
# curl http://cass1-sl.livechatinc.net:9200/_nodes/cache/fields/stats

No handler found for uri [/_nodes/cache/fields/stats] and method [GET]

Thanks for help
Best regards
Marcin Dojwa

**Comment by mdojwa** [comment]
I see that this is available in master only, but how can I install the master version?

# plugin -install bleskes/elasticfacets/master

-> Installing bleskes/elasticfacets/master...
Trying https://github.com/downloads/bleskes/elasticfacets/elasticfacets-master.zip...
Trying https://github.com/bleskes/elasticfacets/zipball/vmaster...
Failed to install bleskes/elasticfacets/master, reason: failed to download

**Comment by mdojwa** [comment]
And after installing it like this: plugin -install bleskes/elasticfacets (I guess this is the master version) the elasticsearch starts with log:
[2013-01-31 20:17:21,095][INFO ][plugins                  ] [Anderssen, Tanya] loaded [knapsack], sites [elasticfacets]

But this still does not work:

# curl -XGET 'http://localhost:9200/_nodes/cache/fields/stats'

No handler found for uri [/_nodes/cache/fields/stats] and method [GET]

**Comment by bleskes** [comment]
Hi mdojwa,

Sorry for responding late. I was travelling. The problems you are having is due to the github disabling their download functionality, which ES used prior to versions 0.20.4 used to download plugins (http://www.elasticsearch.org/blog/2012/12/17/new-download-service.html ) . 

I will put a comment on the readme file saying that installation method work. If you want to install master you'd have to download the code, compile it by hand and place the resulting jar in ES' classpath (plugin folder will do). I will think about hosting it somewhere on a maven repo so you again download it using ES standard mechanisms (version 0.20.4 and up).

It is perhapds insightful to note that in your last attempt ElasticFacets was installed as a site plugin (which is practically a website hosted by ES). Of course, that fails as it is a java based plugin.

Let me know if you need help compiling it.

Boaz

**Comment by mdojwa** [comment]
Thank you for your answer. I need to use master because I want to get 'Cache stats per field', it seems to be very handy function. I downloaded master branch but have no idea how to compile it, I hardly know JAVA :) Could you tell me how to compile it and install under ES ? Thank you very much.

**Comment by bleskes** [comment]
Hi, 

I compiled in on my machine for you. Can you try it by doing ./bin/plugin -install http://bit.ly/elasticfacets-master   ? if it works I will update the readme file.

Cheers,
Boaz

**Comment by mdojwa** [comment]
Hi,

Your command does not work:

# ./bin/plugin -install http://bit.ly/elasticfacets-master

-> Installing http://bit.ly/elasticfacets-master...
Trying http://download.elasticsearch.org/http://-bit.ly.zip...
Trying http://search.maven.org/remotecontent?filepath=http://bit.ly/-bit.ly.zip...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/http://bit.ly/-bit.ly.zip...
Trying https://github.com/http://zipball/vbit.ly... (assuming site plugin)
Failed to install http://bit.ly/elasticfacets-master, reason: failed to download out of all possible locations..., use -verbose to get detailed information

But this one does work:

# ../bin/plugin -url http://bit.ly/elasticfacets-master -install elasticfacets

-> Installing elasticfacets...
Trying http://bit.ly/elasticfacets-master...
Downloading ....DONE
Installed elasticfacets

And ES successfully loads this plugin:
[2013-02-02 17:26:02,003][INFO ][org.leskes.elasticfacets.ElasticFacetsPlugin] ElasticFacets plugin initialized
[2013-02-02 17:26:02,008][INFO ][plugins                  ] [Quincy Harker] loaded [knapsack, ElasticFacetsPlugin], sites []

And test URL works properly:

# curl -XGET 'http://localhost:9200/_nodes/cache/fields/stats'

{"cluster_name":"elasticsearch","nodes":{"PznQIE-XQROgpsEs5R2kPg":{"timestamp":1359822446291,"name":"Quincy Harker","transport_address":"inet[/10.62.21.13:9300]","hostname":"es1.livechat","fields":{}}}}

Thank you very much :)

Best regards.
Marcin Dojwa

**Comment by bleskes** [comment]
Awesome.

Boaz
